# Branding, the public welcome page, and the invitation redirect URL.
#
# The welcome page is the only public surface Collaborate has. A guest lands on
# it after redeeming their invitation, because the portal itself is internal and
# an external person must never need to reach it.
#
# Three rules shape everything in this file:
#
#   1. The page is REGENERATED by the app whenever branding, copy or the host
#      allowlist changes, so nothing an admin can edit is frozen at install time.
#   2. The page is INERT: no network calls, no forms, a restrictive CSP, and the
#      only dynamic behaviour is picking a link out of the query string.
#   3. The redirect target is validated against a HOST ALLOWLIST baked into the
#      page, so the page can never be turned into an open redirect on a
#      company-adjacent URL. The same check runs server side before a target is
#      ever put into an invitation.

function Get-CBFixedAllowedHost {
    <#
    .SYNOPSIS
        Microsoft destinations a guest can legitimately be sent to. Kept separate
        from the tenant's own hosts so the list is easy to audit.
    #>
    return @('teams.microsoft.com', 'myapplications.microsoft.com', 'myaccount.microsoft.com')
}

function Get-CBWelcomeAllowedHost {
    <#
    .SYNOPSIS
        The full redirect allowlist: the tenant's SharePoint and OneDrive hosts
        (resolved from Graph, never configured by hand), the fixed Microsoft
        destinations, and whatever extra hosts the admin added.
    #>
    [CmdletBinding()] param($Settings)
    if (-not $Settings) { $Settings = Get-CBSettings }
    $hosts = [System.Collections.Generic.List[string]]::new()
    try {
        foreach ($h in Get-CBSharePointHosts) { if ($h -and -not $hosts.Contains($h)) { $hosts.Add($h) } }
    }
    catch { Write-Warning "Could not resolve the tenant's SharePoint hosts for the welcome allowlist: $($_.Exception.Message)" }
    foreach ($h in Get-CBFixedAllowedHost) { if (-not $hosts.Contains($h)) { $hosts.Add($h) } }
    foreach ($h in @($Settings.welcome.extraAllowedHosts)) { if ($h -and -not $hosts.Contains($h)) { $hosts.Add($h) } }
    return , $hosts.ToArray()
}

function Get-CBWelcomePageHtml {
    <#
    .SYNOPSIS
        Renders the complete welcome page. Pure: everything it needs is passed in,
        which is what lets the page be unit tested and rendered identically by the
        deploy and by a later save.
    .PARAMETER LogoUrl
        Relative URL of the logo inside the public site (e.g. 'assets/logo-ab12.png'),
        or empty for a text wordmark. Never an absolute URL: 'self' is the only
        image source the CSP permits.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]$Branding,
        [Parameter(Mandatory)]$Welcome,
        [Parameter(Mandatory)][string[]]$AllowedHosts,
        [string]$LogoUrl
    )
    $primary   = ConvertTo-CBHexColor -Value $Branding.primaryColor -Default '#0f5c8c'
    $accent    = ConvertTo-CBHexColor -Value $Branding.accentColor  -Default '#b8501f'
    $onPrimary = Get-CBReadableTextColor -Background $primary
    $onAccent  = Get-CBReadableTextColor -Background $accent

    $company   = ConvertTo-CBHtmlEncoded (ConvertTo-CBBoundedString -Value $Branding.companyName -MaxLength 80 -Default 'Collaborate')
    $headline  = ConvertTo-CBHtmlEncoded (ConvertTo-CBBoundedString -Value $Welcome.headline -MaxLength 80 -Default 'You are in.')
    $message   = ConvertTo-CBHtmlEncoded (ConvertTo-CBBoundedString -Value $Welcome.message -MaxLength 600 -Default '' -AllowNewLines)
    $button    = ConvertTo-CBHtmlEncoded (ConvertTo-CBBoundedString -Value $Welcome.buttonLabel -MaxLength 60 -Default 'Continue')
    $autoJs    = if (ConvertTo-CBBool -Value $Welcome.autoRedirect -Default $false) { 'true' } else { 'false' }

    # The allowlist is emitted as a JSON array. Every entry has already been
    # through ConvertTo-CBHostList, so it can only contain host characters.
    $allowJson = (@($AllowedHosts) | ConvertTo-Json -Compress)
    if ($allowJson -notmatch '^\[') { $allowJson = "[$allowJson]" }   # ConvertTo-Json unwraps a single-element array

    $logoMarkup = if ($LogoUrl) {
        '<img src="' + (ConvertTo-CBHtmlEncoded $LogoUrl) + '" alt="' + $company + '" class="logo" />'
    }
    else {
        '<span class="wordmark">' + $company + '</span>'
    }

    return @"
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src 'self' data:; style-src 'unsafe-inline'; script-src 'unsafe-inline'; form-action 'none'; base-uri 'none'; frame-ancestors 'none'" />
<meta name="robots" content="noindex, nofollow" />
<title>$company</title>
<style>
  :root { --primary: $primary; --on-primary: $onPrimary; --accent: $accent; --on-accent: $onAccent; }
  * { box-sizing: border-box; }
  body { margin: 0; min-height: 100vh; display: flex; align-items: center; justify-content: center;
         font-family: "Segoe UI", system-ui, -apple-system, Arial, sans-serif; color: #201f1e;
         background: #f3f2f1; padding: 24px; }
  .card { width: 100%; max-width: 520px; background: #fff; border-radius: 8px; overflow: hidden;
          box-shadow: 0 2px 16px rgba(0,0,0,.12); }
  .band { background: var(--primary); padding: 20px 24px; }
  .logo { max-height: 44px; max-width: 240px; display: block; }
  .wordmark { color: var(--on-primary); font-size: 20px; font-weight: 600; }
  .body { padding: 28px 24px 32px; }
  h1 { margin: 0 0 12px; font-size: 24px; line-height: 1.25; }
  p { margin: 0 0 16px; line-height: 1.55; white-space: pre-line; }
  .button { display: inline-block; padding: 12px 22px; background: var(--accent); color: var(--on-accent);
            text-decoration: none; border-radius: 4px; font-weight: 600; }
  .foot { margin: 24px 0 0; padding-top: 16px; border-top: 1px solid #edebe9; color: #605e5c; font-size: 12px; }
  .colophon { margin: 6px 0 0; font-size: 10px; color: #a19f9d; }
  .colophon a { color: inherit; text-decoration: none; }
  .colophon a:hover { text-decoration: underline; }
  [hidden] { display: none !important; }
  @media (prefers-color-scheme: dark) {
    body { background: #1b1a19; color: #f3f2f1; }
    .card { background: #252423; box-shadow: none; }
    .foot { border-top-color: #3b3a39; color: #a19f9d; }
    .colophon { color: #797775; }
  }
</style>
</head>
<body>
<main class="card">
  <div class="band">$logoMarkup</div>
  <div class="body">
    <h1>$headline</h1>
    <p>$message</p>
    <p id="targetWrap" hidden><a id="targetLink" class="button" href="#" rel="noopener noreferrer">$button</a></p>
    <p class="foot">$company</p>
    <!-- Attribution, at a tenth the weight of the tenant's own name above it.
         Nothing here is a tracker or a remote request: it is one static link,
         which is why it survives the page's default-src 'none' policy. -->
    <p class="colophon"><a href="https://jsolve.nl" target="_blank" rel="noopener noreferrer">Collaborate by JSolve B.V.</a></p>
  </div>
</main>
<script>
(function () {
  "use strict";
  // Hosts this page is willing to send a guest to. Anything else is ignored, so
  // the page cannot be used as an open redirect. Regenerated whenever an
  // administrator changes the allowlist.
  var ALLOWED = $allowJson;
  var AUTO_REDIRECT = $autoJs;

  function isAllowed(value) {
    var url;
    try { url = new URL(value); } catch (e) { return false; }   // relative or protocol-relative: rejected
    if (url.protocol !== "https:") { return false; }
    var h = url.hostname.toLowerCase();
    for (var i = 0; i < ALLOWED.length; i++) {
      var a = String(ALLOWED[i]).toLowerCase();
      if (!a) { continue; }
      if (a.charAt(0) === ".") {
        if (h === a.slice(1) || (h.length > a.length && h.slice(-a.length) === a)) { return true; }
      } else if (h === a) { return true; }
    }
    return false;
  }

  var params = new URLSearchParams(window.location.search);
  var target = params.get("r");
  if (!target || !isAllowed(target)) { return; }

  var link = document.getElementById("targetLink");
  var label = params.get("rl");
  if (label) { link.textContent = String(label).slice(0, 80); }
  link.setAttribute("href", target);
  document.getElementById("targetWrap").hidden = false;
  if (AUTO_REDIRECT) { window.setTimeout(function () { window.location.replace(target); }, 2500); }
})();
</script>
</body>
</html>
"@
}

function Get-CBBrandingManifest {
    <#
    .SYNOPSIS
        The small public branding file the portal's sign-in screen reads. It runs
        before any token exists, so it cannot call the API; publishing branding
        here is what keeps even the pre-sign-in view current.
    .NOTES
        Contains display values only. Nothing here is sensitive: it is the same
        information printed on every email that leaves the tenant.
    #>
    [CmdletBinding()] param([Parameter(Mandatory)]$Branding, [string]$LogoUrl)
    return ([ordered]@{
            companyName    = "$($Branding.companyName)"
            portalTitle    = "$($Branding.portalTitle)"
            portalSubtitle = "$($Branding.portalSubtitle)"
            primaryColor   = "$($Branding.primaryColor)"
            accentColor    = "$($Branding.accentColor)"
            logoUrl        = "$LogoUrl"
            updatedUtc     = [DateTimeOffset]::UtcNow.ToString('o')
        } | ConvertTo-Json -Depth 5)
}

function Publish-CBWelcomeSite {
    <#
    .SYNOPSIS
        Renders and publishes the welcome page, the public branding manifest and
        the logo, then records the published page's hash so tampering can be
        detected later.
    .DESCRIPTION
        Called on every branding, welcome-copy or allowlist save, and by the
        deploy so the very first publish runs through exactly the same code.
        Returns the settings object (with the recorded hash) so the caller can
        persist it.
    #>
    [CmdletBinding()] param($Settings, [string]$Actor, [byte[]]$LogoBytes)
    if (-not $Settings) { $Settings = Get-CBSettings }
    if (-not (Test-CBPublicSiteConfigured)) {
        Write-Warning 'No public welcome site is configured; skipping publish.'
        return $Settings
    }

    # Assets live INSIDE the static site container, not in a container of their
    # own, so they are same-origin with the page. That is what lets the page keep
    # img-src 'self': a logo served from the blob endpoint would be a different
    # origin and the browser would refuse it.
    $logoUrl = ''
    if ($Settings.branding.logoFile) {
        try {
            # Assigned inside the branches, never as `$bytes = if (...) {...}`:
            # an if-expression puts its result through the output stream, which
            # unrolls a byte[] into an Object[]. That is how a perfectly good
            # PNG stops being a PNG as far as every later type check is
            # concerned.
            [byte[]]$bytes = @()
            if ($LogoBytes -and $LogoBytes.Length -gt 0) {
                # A freshly uploaded logo is passed straight through. Re-reading
                # it from storage to publish the copy we are already holding adds
                # a round trip and a chance to mangle it, for nothing.
                $bytes = $LogoBytes
            }
            else {
                $bytes = Get-CBBlobBytes -Name ("branding/" + $Settings.branding.logoFile)
            }

            if ($bytes -and $bytes.Length -gt 0) {
                $name = 'assets/' + $Settings.branding.logoFile
                Publish-CBPublicBlob -Container '$web' -Name $name `
                    -ContentType $Settings.branding.logoContentType -CacheSeconds 3600 -Content $bytes
                $logoUrl = 'assets/' + $Settings.branding.logoFile

                # What the site is actually serving, against what we sent. Both a
                # good image and a mangled one answer 200, so the size is the
                # cheapest thing that can tell them apart, and a logo that
                # silently does not render is the whole reason this check exists.
                $published = Get-CBPublicBlobLength -Container '$web' -Name $name
                if ($published -ge 0 -and $published -ne $bytes.Length) {
                    throw "the public site is serving $published bytes for it, but it is $($bytes.Length) bytes"
                }
            }
            else { throw 'the image could not be read back from storage' }
        }
        catch {
            # Loud when somebody is uploading a logo right now, because a
            # swallowed failure here leaves the settings pointing at an asset
            # that does not exist: a broken icon in the portal, a wordmark on the
            # welcome page, and nothing anywhere saying why. Quiet on a republish
            # (a colour change), where a stale logo should not block the save.
            $detail = "Could not publish the logo to the public site: $($_.Exception.Message)."
            if ($LogoBytes -and $LogoBytes.Length -gt 0) { throw $detail }
            Write-Warning $detail
        }
    }

    $allowed = Get-CBWelcomeAllowedHost -Settings $Settings
    $html = Get-CBWelcomePageHtml -Branding $Settings.branding -Welcome $Settings.welcome -AllowedHosts $allowed -LogoUrl $logoUrl
    Publish-CBPublicBlob -Container '$web' -Name 'welcome.html' -Content $html -ContentType 'text/html; charset=utf-8' -CacheSeconds 60
    # index.html is the static-site default document, so a bare URL works too.
    Publish-CBPublicBlob -Container '$web' -Name 'index.html' -Content $html -ContentType 'text/html; charset=utf-8' -CacheSeconds 60

    # The portal's sign-in screen reads this, so it needs an absolute URL there;
    # the welcome page reads nothing and uses the relative logo path above.
    try {
        Publish-CBPublicBlob -Container '$web' -Name 'assets/branding.json' `
            -Content (Get-CBBrandingManifest -Branding $Settings.branding -LogoUrl (Get-CBPublicLogoUrl -Settings $Settings)) `
            -ContentType 'application/json; charset=utf-8' -CacheSeconds 60
    }
    catch { Write-Warning "Could not publish the public branding manifest: $($_.Exception.Message)" }

    $Settings.welcome.publishedHash = Get-CBTextHash -Text $html
    $Settings.welcome.publishedUtc = [DateTimeOffset]::UtcNow.ToString('o')
    Write-CBSystemActivity -EventName 'Welcome page published' -Actor $Actor -Detail @{
        allowedHosts = ($allowed -join ', ')
        logo         = $(if ($logoUrl) { $logoUrl } else { '(wordmark)' })
        hash         = $Settings.welcome.publishedHash
    }
    return $Settings
}

function Test-CBWelcomePagePublished {
    <#
    .SYNOPSIS
        Compares the published page against the hash recorded when the app last
        wrote it. Drift means somebody or something else rewrote a page we serve
        to external parties, which the Watchdog reports.
    .OUTPUTS
        @{ Checked; Match; Reason }
    #>
    [CmdletBinding()] param($Settings)
    if (-not $Settings) { $Settings = Get-CBSettings }
    if (-not (Test-CBPublicSiteConfigured)) { return @{ Checked = $false; Match = $true; Reason = 'no public site configured' } }
    if (-not $Settings.welcome.publishedHash) { return @{ Checked = $false; Match = $true; Reason = 'never published' } }
    try {
        $current = Get-CBPublicBlobText -Container '$web' -Name 'welcome.html'
        if ($null -eq $current) { return @{ Checked = $true; Match = $false; Reason = 'the published welcome page is missing' } }
        $hash = Get-CBTextHash -Text $current
        if ($hash -eq $Settings.welcome.publishedHash) { return @{ Checked = $true; Match = $true; Reason = '' } }
        return @{ Checked = $true; Match = $false; Reason = 'the published welcome page does not match what Collaborate last wrote' }
    }
    catch { return @{ Checked = $false; Match = $true; Reason = "could not read the published page: $($_.Exception.Message)" } }
}

function Set-CBBrandingLogo {
    <#
    .SYNOPSIS
        Stores an uploaded logo. The master copy goes to the private state
        account; Publish-CBWelcomeSite mirrors it to the public site.
    .DESCRIPTION
        Content is validated by MAGIC BYTES, not by the caller's claimed type or
        file name, and the stored name is generated here. A caller therefore
        cannot choose what gets written or talk the public page into pointing at
        something else.
    .OUTPUTS
        @{ FileName; ContentType }
    #>
    [CmdletBinding()] param([Parameter(Mandatory)][byte[]]$Bytes)
    if ($Bytes.Length -lt 8) { throw 'That file is empty or truncated.' }
    if ($Bytes.Length -gt 524288) { throw 'The logo must be 512 KB or smaller.' }

    $isPng = ($Bytes[0] -eq 0x89 -and $Bytes[1] -eq 0x50 -and $Bytes[2] -eq 0x4E -and $Bytes[3] -eq 0x47 -and
        $Bytes[4] -eq 0x0D -and $Bytes[5] -eq 0x0A -and $Bytes[6] -eq 0x1A -and $Bytes[7] -eq 0x0A)
    $isJpeg = ($Bytes[0] -eq 0xFF -and $Bytes[1] -eq 0xD8 -and $Bytes[2] -eq 0xFF)
    if (-not ($isPng -or $isJpeg)) { throw 'The logo must be a PNG or JPEG image.' }

    $contentType = if ($isPng) { 'image/png' } else { 'image/jpeg' }
    $extension = if ($isPng) { 'png' } else { 'jpg' }
    # A new name on every upload defeats caching of the old image on the public
    # site (and in the mail clients that have already seen it).
    $name = 'logo-{0}.{1}' -f ([Guid]::NewGuid().ToString('N').Substring(0, 8)), $extension

    Set-CBBlobBytes -Name ("branding/$name") -Bytes $Bytes -ContentType $contentType
    return @{ FileName = $name; ContentType = $contentType }
}

function Get-CBWelcomeUrl {
    <#
    .SYNOPSIS
        Builds the invitation redirect URL: where a guest lands after redeeming.
    .DESCRIPTION
        Only two things vary per invitation, and both are validated here as well
        as on the page itself: the target the guest should open, and its label.
        An unrecognised target is dropped rather than rejected, so an invitation
        never fails because of a link.
    #>
    [CmdletBinding()]
    param([string]$TargetUrl, [string]$TargetLabel, $Settings, [string[]]$AllowedHosts)
    $cfg = Get-CBConfig
    if (-not $cfg.PublicSiteUrl) { throw 'The public welcome site URL is not configured (CB_PUBLIC_SITE_URL). Re-run the deployment.' }
    $base = $cfg.PublicSiteUrl.TrimEnd('/') + '/welcome.html'
    if (-not $TargetUrl) { return $base }

    if (-not $AllowedHosts) {
        if (-not $Settings) { $Settings = Get-CBSettings }
        $AllowedHosts = Get-CBWelcomeAllowedHost -Settings $Settings
    }
    if (-not (Test-CBUrlAllowed -Url $TargetUrl -AllowedHosts $AllowedHosts)) {
        Write-Warning "Redirect target '$TargetUrl' is not in the welcome-page allowlist; the invitation will not carry a link."
        return $base
    }

    $query = 'r=' + [Uri]::EscapeDataString($TargetUrl)
    if ($TargetLabel) {
        $label = ConvertTo-CBBoundedString -Value $TargetLabel -MaxLength 80
        if ($label) { $query += '&rl=' + [Uri]::EscapeDataString($label) }
    }
    return "$base`?$query"
}
